theme: jekyll-theme-architect
title: Adder's Pai Sho
description: my contributions to the Pai Sho community
show_downloads: false
permalink: adderspaisho/:title

github:
  is_project_page: false

collections:
  - pages